[package]
name = "hanzzok"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
eyre = "0.6.5"
libhanzzok = "0.1.0"
